testing_openai_base_url: "https://o8kjqm58o8ogcm5ek8aggddkb5ggk8dp.openapi-sj.sii.edu.cn/v1"
testing_api_key_env: "INF_API_KEY_PRO"
testing_model: "ds-v4-pro"

target_openai_base_url: "https://ds-v4-flash-w8a8-vllm-ascend.openapi-sj.sii.edu.cn/v1"
target_api_key_env: "INF_API_KEY_FLASH"
target_model: "ds-v4-flash"
